steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", ".env"]
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/buku-tukar:${SHORT_SHA}", "."]
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/buku-tukar:${SHORT_SHA}"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "buku-tukar",
        "--image",
        "gcr.io/$PROJECT_ID/buku-tukar:${SHORT_SHA}",
        "--timeout",
        "1000s",
        "--port",
        "5003",
        "--region",
        "us-central1",
        "--allow-unauthenticated"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
